name: ci
on: push

jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: run pylint
        uses: ./.github/actions/pylint

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: run pytest
        uses: ./
        with:
          entrypoint: ./.github/actions/pytest/entrypoint.sh
